#ifndef VIT_OCL_BACKEND_H
#define VIT_OCL_BACKEND_H

#include <CL/cl.h>

typedef struct {
    cl_platform_id platform;
    cl_device_id device;
    cl_context context;
    cl_command_queue queue;
    cl_program program;
    cl_kernel kernel_embed;
    cl_kernel kernel_layernorm;
    cl_kernel kernel_qkv_proj;
    cl_kernel kernel_attention;
    cl_kernel kernel_ffn;
    cl_kernel kernel_head;
    cl_kernel kernel_add;
    cl_kernel kernel_clip_grad_norm;
    cl_kernel kernel_scale_grads;
    cl_kernel kernel_adamw_update;
    cl_kernel kernel_mpp_forward;
    cl_kernel kernel_mpp_backward;
    cl_kernel kernel_embed_bwd;
    cl_kernel kernel_layernorm_bwd;
    cl_kernel kernel_qkv_proj_bwd;
    cl_kernel kernel_attention_bwd;
    cl_kernel kernel_ffn_bwd;
    cl_kernel kernel_head_bwd;
    cl_mem d_input;
    cl_mem d_output;
    cl_mem d_weights;
    cl_mem d_biases;
    cl_mem d_gradWeights;
    cl_mem d_gradBiases;
    cl_mem d_mWeights;
    cl_mem d_vWeights;
    cl_mem d_mBiases;
    cl_mem d_vBiases;
    cl_mem d_token_embeds;
    cl_mem d_layernorm_input;
    cl_mem d_qkv_proj;
    cl_mem d_attn_output;
    cl_mem d_ffn_output;
    cl_mem d_head_input;
    cl_mem d_layernorm_mean;
    cl_mem d_layernorm_inv_std;
    cl_mem d_attn_weights;
    cl_mem d_pre_gelu;
    cl_mem d_ffn_hidden;
    cl_mem d_cls_normed;
    cl_mem d_cls_mean;
    cl_mem d_cls_inv_std;
    cl_mem d_grad_qkv;
    cl_mem d_grad_norm;
    cl_mem d_mpp_logits;
    cl_mem d_mpp_loss;
    cl_mem d_mask_weights;
    cl_mem d_mask_biases;
    cl_mem d_grad_mask_weights;
    cl_mem d_grad_mask_biases;
    cl_mem d_m_mask_weights;
    cl_mem d_v_mask_weights;
    cl_mem d_m_mask_biases;
    cl_mem d_v_mask_biases;
    cl_mem d_layer_inputs;
    cl_mem d_ln1_outputs;
    cl_mem d_ln2_inputs;
    cl_mem d_attn_temp;
    cl_mem d_scores_temp;
    cl_mem d_ffn_temp;
    cl_mem d_normed_temp;
    float* host_weights;
    float* host_biases;
    float* host_mWeights;
    float* host_vWeights;
    float* host_mBiases;
    float* host_vBiases;
    int embed_dim;
    int num_layers;
    int num_heads;
    int mlp_dim;
    int seq_len;
    int in_channels;
    int total_weights;
    int total_biases;
    int max_allocated_batch;
    int mpp_num_classes;
    int max_batch_size;
    size_t workgroup_size;
    float init_std;
    int initialized;
} VitBackend;

VitBackend* vit_backend_create(int embed_dim, int num_layers, int num_heads, int mlp_dim, int seq_len, int in_channels, long seed, int mppNumClasses);
VitBackend* vit_backend_create_with_weights(int embed_dim, int num_layers, int num_heads, int mlp_dim, int seq_len, int in_channels, const float* weights, const float* biases, int mppNumClasses);
void vit_backend_destroy(VitBackend* backend);
void vit_backend_forward(VitBackend* backend, const float* input, float* output, int batch_size);
void vit_backend_backward(VitBackend* backend, const float* input, const float* label, const float* grad_output, int batch_size);
void vit_backend_adamw_update(VitBackend* backend, int batch_size, float lr, float beta1, float beta2, float epsilon, float weight_decay, int step);
void vit_backend_clip_gradients(VitBackend* backend, float max_norm);
void vit_backend_zero_gradients(VitBackend* backend);
void vit_backend_get_weights(VitBackend* backend, float* out);
void vit_backend_get_biases(VitBackend* backend, float* out);
void vit_backend_set_weights(VitBackend* backend, const float* weights);
void vit_backend_set_biases(VitBackend* backend, const float* biases);
int vit_backend_get_total_weights(VitBackend* backend);
int vit_backend_get_total_biases(VitBackend* backend);
float vit_backend_mpp_forward(VitBackend* backend, const int* mask_indices, const int* targets, int batch_size, int num_masked, int num_classes);
void vit_backend_mpp_backward(VitBackend* backend, const int* mask_indices, const int* targets, int batch_size, int num_masked, int num_classes, float loss_scale);
void vit_backend_get_gradients(VitBackend* backend, float* out);

#endif